bcgov/pubcode

README.md

Resolves #17 
---
[Backend](https://public-code-18-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://public-code-18-frontend.apps.silver.devops.gov.bc.ca/) available

Feat: badges for issues, PRs, license, lifecycle

---

.github/workflows/pubcode-crawler-on-scheduler.yml
crawler/package-lock.json
crawler/package.json
crawler/src/main.js

1.1 On Demand.
1.2 On Schedule.
---
[Frontend](https://public-code-50-frontend.apps.silver.devops.gov.bc.ca/) available

1. Added workflow file for running the crawler.

---

.github/workflows/merge-main.yml
.github/workflows/pr-open.yml
.github/workflows/tests.yml
SECURITY.md
common/openshift.init.yml
database/Dockerfile
database/openshift.deploy.yml
docker-compose.yml

MongoDb
---
[Frontend](https://public-code-65-frontend.apps.silver.devops.gov.bc.ca/) available

Feat: mongodb

---

frontend/src/components/EditForm.jsx

---
[Frontend](https://public-code-75-frontend.apps.silver.devops.gov.bc.ca/) available

fix: handle invalid GH link in edit

---

database/openshift.deploy.yml

---
[Frontend](https://public-code-76-frontend.apps.silver.devops.gov.bc.ca/) available

Bump Mongo PVC to 512Mi

---

.github/workflows/merge-main.yml
.github/workflows/pr-open.yml
backend/Dockerfile
backend/openshift.deploy.yml
backend/package-lock.json
backend/package.json
backend/src/app.js
backend/src/db/database.js
backend/src/entities/pub-code-entity.js
backend/src/logger.js
backend/src/routes/pubcode-router.js
backend/src/server.js
backend/src/services/pub-code-service.js
common/openshift.init.yml
database/openshift.deploy.yml
docker-compose.yml

feat: API code
---
[Frontend](https://public-code-79-frontend.apps.silver.devops.gov.bc.ca/) available

feat: initial commit to get the api up and running in openshift.

---

backend/Dockerfile
database/Dockerfile
frontend/Dockerfile

---
[Frontend](https://public-code-81-frontend.apps.silver.devops.gov.bc.ca/) available

Docker adjustments, health checks

---

.github/workflows/merge-main.yml
.github/workflows/pr-close.yml

Prepare TEST and PROD OpenShift deployments.
---
[Frontend](https://public-code-86-frontend.apps.silver.devops.gov.bc.ca/) available

pr-close + promotions for database and backend

---

backend/openshift.deploy.yml
database/openshift.deploy.yml
frontend/openshift.deploy.yml

Pretty close after TEST deployments.  Mostly needs small changes and a fix to initContainers in the db.
---
[Frontend](https://public-code-87-frontend.apps.silver.devops.gov.bc.ca/) available

PROD deployment

---

backend/src/services/pub-code-service.js

---
[Frontend](https://public-code-89-frontend.apps.silver.devops.gov.bc.ca/) available

speed up query and dont wait for bulk-load

---

backend/package-lock.json
backend/package.json
backend/src/app.js
backend/src/routes/pubcode-router.js

---
[Frontend](https://public-code-93-frontend.apps.silver.devops.gov.bc.ca/) available
[Backend](https://public-code-93-backend.apps.silver.devops.gov.bc.ca/) available

code changes for adding rate limiting.

---

.github/workflows/pubcode-crawler-on-scheduler.yml
crawler/src/main.js

---
[Frontend](https://public-code-100-frontend.apps.silver.devops.gov.bc.ca/) available
[Backend](https://public-code-100-backend.apps.silver.devops.gov.bc.ca/) available

Test crawler cronjob/dispatch rights

---

.github/workflows/pubcode-crawler-on-scheduler.yml
crawler/src/main.js

---
[Frontend](https://public-code-101-frontend.apps.silver.devops.gov.bc.ca/) available
[Backend](https://public-code-101-backend.apps.silver.devops.gov.bc.ca/) available

Provide API key to crawler

---

README.md
backend/README.md
frontend/README.md
schema/README.md

---
[Frontend](https://public-code-103-frontend.apps.silver.devops.gov.bc.ca/) available
[Backend](https://public-code-103-backend.apps.silver.devops.gov.bc.ca/) available

documentation updates.

---

.github/workflows/pubcode-crawler-on-scheduler.yml
backend/src/entities/pub-code-entity.js
backend/src/services/pub-code-service.js
crawler/src/main.js
frontend/README.md

---
[Frontend](https://public-code-109-frontend.apps.silver.devops.gov.bc.ca/) available
[Backend](https://public-code-109-backend.apps.silver.devops.gov.bc.ca/) available

Added API call from crawler.

---

bcgovpubcode.yml
frontend/src/components/FormComponent.jsx

---
[Frontend](https://public-code-130-frontend.apps.silver.devops.gov.bc.ca/) available
[Backend](https://public-code-130-backend.apps.silver.devops.gov.bc.ca/) available

Bug Fix to populate required field version in the YAML

---

backend/src/app.js
backend/src/schedulers/refresh-cache.js
backend/src/server.js

---
[Frontend](https://public-code-142-frontend.apps.silver.devops.gov.bc.ca/) available
[Backend](https://public-code-142-backend.apps.silver.devops.gov.bc.ca/) available

refresh cache and reduce log noise

---

backend/src/services/cache-service.js

---
[Frontend](https://public-code-144-frontend.apps.silver.devops.gov.bc.ca/) available
[Backend](https://public-code-144-backend.apps.silver.devops.gov.bc.ca/) available

replace cache entries instead of infinitely adding items to it.

---

.github/ISSUE_TEMPLATE/schema.md

---
[Frontend](https://public-code-139-frontend.apps.silver.devops.gov.bc.ca/) available
[Backend](https://public-code-139-backend.apps.silver.devops.gov.bc.ca/) available

Basic schema issue type

---

.github/workflows/pr-open.yml
common/openshift.init.yml

---
[API](https://pubcode-151-api.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://pubcode-151.apps.silver.devops.gov.bc.ca/) available

Rebuild images

---

.github/workflows/pubcode-crawler-on-scheduler.yml

---
[API](https://pubcode-156-api.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://pubcode-156.apps.silver.devops.gov.bc.ca/) available

Get crawler URL from route

---

.github/workflows/pubcode-crawler-on-scheduler.yml

---
[API](https://pubcode-158-api.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://pubcode-158.apps.silver.devops.gov.bc.ca/) available

Add https:// to crawler url

---

api/src/entities/pub-code-entity.js
crawler/src/main.js
frontend/Caddyfile

1. stars
2. watchers
3. last updated
4. license
---
[API](https://pubcode-160-api.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://pubcode-160.apps.silver.devops.gov.bc.ca/) available

Add few extra fields to crawler for nice visualization

---

.github/workflows/pubcode-crawler-on-scheduler.yml
api/src/entities/pub-code-entity.js
crawler/src/main.js
frontend/src/components/EditForm.jsx
frontend/src/components/FormComponent.jsx
schema/bcgovpubcode.json

feat:
1. change bcgov_pubcode_version to version
2. add --- to beginning of generated yaml
3. read both bcgovpubcode.yaml and bcgovpubcode.yml
4. support one of repo crawl in the crawler module through workflow dispatch
5. Add last_update date check so that only recently updated repos are searched for the file.
---
[API](https://pubcode-162-api.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://pubcode-162.apps.silver.devops.gov.bc.ca/) available

feat: multiple improvements

---

api/.dockerignore
frontend/.dockerignore
frontend/package.json
frontend/vite.config.js

---
[API](https://pubcode-167-api.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://pubcode-167.apps.silver.devops.gov.bc.ca/) available

add manual chunks to reduce huge js load

---

database/Dockerfile
database/mongod.conf

---
[API](https://pubcode-171-api.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://pubcode-171.apps.silver.devops.gov.bc.ca/) available

add mongo config to restrict volume

---

api/package-lock.json
api/package.json
frontend/Caddyfile
frontend/package-lock.json
frontend/package.json

---
[API](https://pubcode-177-api.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://pubcode-177.apps.silver.devops.gov.bc.ca/) available

upgrade dependencies and format Caddyfile

---

api/Dockerfile
database/Dockerfile

Digests make projects dependent on Renovate.
---
[API](https://pubcode-182-api.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://pubcode-182.apps.silver.devops.gov.bc.ca/) available

Clip digests

---

.github/dependabot.yml

---
[API](https://pubcode-186-api.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://pubcode-186.apps.silver.devops.gov.bc.ca/) available

Enable Dependabot (while Renovate is blocked)

---

.github/workflows/pr-open.yml
database/openshift.deploy.yml

Reduce PVC size for DEV PRs to prevent running out of space/allocations.
---
[API](https://pubcode-190-api.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://pubcode-190.apps.silver.devops.gov.bc.ca/) available

Reduce DEV PVC size

---

.github/workflows/merge-main.yml
.github/workflows/pr-open.yml
.github/workflows/prod.yml
api/Dockerfile
api/openshift.deploy.yml
api/package-lock.json
api/package.json
api/src/email/ches-service.js
api/src/email/connection.js
api/src/email/index.js
api/src/services/pub-code-service.js
common/openshift.init.yml

Integration with CHES for error notifications and updates to dockerfile.
---
[API](https://pubcode-202-api.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://pubcode-202.apps.silver.devops.gov.bc.ca/) available

Changes to integrate with CHES for email notification in failures.

---

.github/workflows/merge-main.yml
.github/workflows/prod.yml

zone was incorrect after last merge, fixed it.
---
[API](https://pubcode-206-api.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://pubcode-206.apps.silver.devops.gov.bc.ca/) available

workflow fixes.

---

frontend/Caddyfile
frontend/openshift.deploy.yml

---
[API](https://pubcode-218-api.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://pubcode-218.apps.silver.devops.gov.bc.ca/) available

217 set log level for caddy

---

api/src/services/pub-code-service.js

---
[API](https://pubcode-233-api.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://pubcode-233.apps.silver.devops.gov.bc.ca/) available

handle multiple recipients for email.

---

.github/workflows/merge-main.yml
.github/workflows/tests.yml

---
[API](https://pubcode-248-api.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://pubcode-248.apps.silver.devops.gov.bc.ca/) available

247 align main merge workflow to run on pull request completed

---

.github/workflows/pr-open.yml

resource updates
---
[API](https://pubcode-251-api.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://pubcode-251.apps.silver.devops.gov.bc.ca/) available

resource updates for pr deployments

---

api/package-lock.json
api/package.json
api/src/db/database.js

---
[API](https://pubcode-253-api.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://pubcode-253.apps.silver.devops.gov.bc.ca/) available

retry db connection

---

frontend/package-lock.json
frontend/package.json

---
[API](https://pubcode-272-api.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://pubcode-272.apps.silver.devops.gov.bc.ca/) available

fix: override for subdep security alert

---

.github/workflows/merge-main.yml
frontend/cypress.config.js
frontend/cypress/support/index.js

---
[API](https://pubcode-273-api.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://pubcode-273.apps.silver.devops.gov.bc.ca/) available

ci: bump changelog action, stop silently failing

---

charts/pubcode/templates/secret.yaml

---
[API](https://pubcode-280-api.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://pubcode-280.apps.silver.devops.gov.bc.ca/) available

fix: reuse API KEY if it is already available.

---

charts/pubcode/Chart.yaml
charts/pubcode/values.yaml

---
[API](https://pubcode-300-api.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://pubcode-300.apps.silver.devops.gov.bc.ca/) available

update helm service version

---

.github/workflows/merge.yml

---
[API](https://pubcode-346-api.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://pubcode-346.apps.silver.devops.gov.bc.ca/) available

chore(ci): use default CodeQL

---

api/Dockerfile
frontend/Dockerfile

Closes #344
---
[API](https://pubcode-345-api.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://pubcode-345.apps.silver.devops.gov.bc.ca/) available

chore(ci): node 22 (and drop alpine)

---

.github/workflows/merge.yml
.github/workflows/pr-close.yml
.github/workflows/pr-open.yml
.github/workflows/scheduled.yml

---
[API](https://pubcode-369-api.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://pubcode-369.apps.silver.devops.gov.bc.ca/) available

chore(ci): handle gh runner oc removal

---

charts/pubcode/values.yaml

---
[API](https://pubcode-402-api.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://pubcode-402.apps.silver.devops.gov.bc.ca/) available

chore: remove limits

---

.github/workflows/pr-open.yml

---
[API](https://pubcode-407-api.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://pubcode-407.apps.silver.devops.gov.bc.ca/) available

chore(ci): actions moved to bcgov org

---

renovate.json

---
[API](https://pubcode-412-api.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://pubcode-412.apps.silver.devops.gov.bc.ca/) available

chore(ci): try pinning digests with Renovate

---

.github/workflows/.deploy.yml
.github/workflows/merge.yml
.github/workflows/pr-open.yml
charts/pubcode/Chart.lock

---
[API](https://pubcode-416-api.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://pubcode-416.apps.silver.devops.gov.bc.ca/) available

fix: pipeline

---

renovate.json

---
[API](https://pubcode-417-api.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://pubcode-417.apps.silver.devops.gov.bc.ca/) available

chore(ci): opt into Renovate vulnerability alerts

---

charts/pubcode/values.yaml
crawler/src/main.js
frontend/Caddyfile
schema/bcgovpubcode.json

---
[API](https://pubcode-424-api.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://pubcode-424.apps.silver.devops.gov.bc.ca/) available

feat: partner ministry

---

schema/bcgovpubcode.json

---
[API](https://pubcode-426-api.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://pubcode-426.apps.silver.devops.gov.bc.ca/) available

feat: add other tools option

---

.github/workflows/.deploy.yml
.github/workflows/pr-open.yml
.gitignore
charts/pubcode/templates/secret.yaml
charts/pubcode/values.yaml
frontend/Caddyfile
frontend/src/components/Dashboard.jsx
frontend/src/components/LeftDrawer.jsx
frontend/src/components/PowerBIDashboard.jsx
frontend/src/routes/index.jsx

---
[API](https://pubcode-452-api.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://pubcode-452.apps.silver.devops.gov.bc.ca/) available

feat: trying pubcode dashboard

---

.github/workflows/pr-close.yml

---
[API](https://pubcode-456-api.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://pubcode-456.apps.silver.devops.gov.bc.ca/) available

fix: remove database from being tagged

---

.github/workflows/pr-close.yml
.github/workflows/pr-open.yml

---
[API](https://pubcode-457-api.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://pubcode-457.apps.silver.devops.gov.bc.ca/) available

fix: triggers

---

frontend/src/components/Dashboard.jsx

---
[API](https://pubcode-458-api.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://pubcode-458.apps.silver.devops.gov.bc.ca/) available

feat: changing landing page

---

frontend/cypress/e2e/home-page.cy.js
frontend/src/components/Dashboard.jsx
frontend/src/components/LeftDrawer.jsx

---
[API](https://pubcode-460-api.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://pubcode-460.apps.silver.devops.gov.bc.ca/) available

chore: dashboard and drawer changes

---

frontend/src/components/LeftDrawer.jsx

---
[API](https://pubcode-461-api.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://pubcode-461.apps.silver.devops.gov.bc.ca/) available

fix: cutoff

---

.github/workflows/scheduled.yml

---
[API](https://pubcode-466-api.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://pubcode-466.apps.silver.devops.gov.bc.ca/) available

chore: run at 4pm

---

.github/workflows/pr-open.yml

---
[API](https://pubcode-470-api.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://pubcode-470.apps.silver.devops.gov.bc.ca/) available

chore: trying multiple tags

---

renovate.json

---
[API](https://pubcode-471-api.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://pubcode-471.apps.silver.devops.gov.bc.ca/) available

chore(ci)) renovate minimumReleaseAge=0

---

api/Dockerfile
database/Dockerfile
docker-compose.yml
frontend/Dockerfile

---
[API](https://pubcode-478-api.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://pubcode-478.apps.silver.devops.gov.bc.ca/) available

chore(ci): drop docker digests

---

api/Dockerfile

Please provide a summary of the change and the issue fixed. Please include relevant context. List dependency changes.
Fixes # (issue)
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
---
[API](https://pubcode-486-api.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://pubcode-486.apps.silver.devops.gov.bc.ca/) available

chore(ci): update Dockerfile ENV syntax
